require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CargofuncionariosController do

  # This should return the minimal set of attributes required to create a valid
  # Cargofuncionario. As you add validations to Cargofuncionario, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cargofuncionario" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CargofuncionariosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cargofuncionarios as @cargofuncionarios" do
      cargofuncionario = Cargofuncionario.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cargofuncionarios).should eq([cargofuncionario])
    end
  end

  describe "GET show" do
    it "assigns the requested cargofuncionario as @cargofuncionario" do
      cargofuncionario = Cargofuncionario.create! valid_attributes
      get :show, {:id => cargofuncionario.to_param}, valid_session
      assigns(:cargofuncionario).should eq(cargofuncionario)
    end
  end

  describe "GET new" do
    it "assigns a new cargofuncionario as @cargofuncionario" do
      get :new, {}, valid_session
      assigns(:cargofuncionario).should be_a_new(Cargofuncionario)
    end
  end

  describe "GET edit" do
    it "assigns the requested cargofuncionario as @cargofuncionario" do
      cargofuncionario = Cargofuncionario.create! valid_attributes
      get :edit, {:id => cargofuncionario.to_param}, valid_session
      assigns(:cargofuncionario).should eq(cargofuncionario)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cargofuncionario" do
        expect {
          post :create, {:cargofuncionario => valid_attributes}, valid_session
        }.to change(Cargofuncionario, :count).by(1)
      end

      it "assigns a newly created cargofuncionario as @cargofuncionario" do
        post :create, {:cargofuncionario => valid_attributes}, valid_session
        assigns(:cargofuncionario).should be_a(Cargofuncionario)
        assigns(:cargofuncionario).should be_persisted
      end

      it "redirects to the created cargofuncionario" do
        post :create, {:cargofuncionario => valid_attributes}, valid_session
        response.should redirect_to(Cargofuncionario.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cargofuncionario as @cargofuncionario" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cargofuncionario.any_instance.stub(:save).and_return(false)
        post :create, {:cargofuncionario => { "cargofuncionario" => "invalid value" }}, valid_session
        assigns(:cargofuncionario).should be_a_new(Cargofuncionario)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cargofuncionario.any_instance.stub(:save).and_return(false)
        post :create, {:cargofuncionario => { "cargofuncionario" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cargofuncionario" do
        cargofuncionario = Cargofuncionario.create! valid_attributes
        # Assuming there are no other cargofuncionarios in the database, this
        # specifies that the Cargofuncionario created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cargofuncionario.any_instance.should_receive(:update).with({ "cargofuncionario" => "MyString" })
        put :update, {:id => cargofuncionario.to_param, :cargofuncionario => { "cargofuncionario" => "MyString" }}, valid_session
      end

      it "assigns the requested cargofuncionario as @cargofuncionario" do
        cargofuncionario = Cargofuncionario.create! valid_attributes
        put :update, {:id => cargofuncionario.to_param, :cargofuncionario => valid_attributes}, valid_session
        assigns(:cargofuncionario).should eq(cargofuncionario)
      end

      it "redirects to the cargofuncionario" do
        cargofuncionario = Cargofuncionario.create! valid_attributes
        put :update, {:id => cargofuncionario.to_param, :cargofuncionario => valid_attributes}, valid_session
        response.should redirect_to(cargofuncionario)
      end
    end

    describe "with invalid params" do
      it "assigns the cargofuncionario as @cargofuncionario" do
        cargofuncionario = Cargofuncionario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cargofuncionario.any_instance.stub(:save).and_return(false)
        put :update, {:id => cargofuncionario.to_param, :cargofuncionario => { "cargofuncionario" => "invalid value" }}, valid_session
        assigns(:cargofuncionario).should eq(cargofuncionario)
      end

      it "re-renders the 'edit' template" do
        cargofuncionario = Cargofuncionario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cargofuncionario.any_instance.stub(:save).and_return(false)
        put :update, {:id => cargofuncionario.to_param, :cargofuncionario => { "cargofuncionario" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cargofuncionario" do
      cargofuncionario = Cargofuncionario.create! valid_attributes
      expect {
        delete :destroy, {:id => cargofuncionario.to_param}, valid_session
      }.to change(Cargofuncionario, :count).by(-1)
    end

    it "redirects to the cargofuncionarios list" do
      cargofuncionario = Cargofuncionario.create! valid_attributes
      delete :destroy, {:id => cargofuncionario.to_param}, valid_session
      response.should redirect_to(cargofuncionarios_url)
    end
  end

end
