require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItensdopedidosController do

  # This should return the minimal set of attributes required to create a valid
  # Itensdopedido. As you add validations to Itensdopedido, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "itempedido" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItensdopedidosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all itensdopedidos as @itensdopedidos" do
      itensdopedido = Itensdopedido.create! valid_attributes
      get :index, {}, valid_session
      assigns(:itensdopedidos).should eq([itensdopedido])
    end
  end

  describe "GET show" do
    it "assigns the requested itensdopedido as @itensdopedido" do
      itensdopedido = Itensdopedido.create! valid_attributes
      get :show, {:id => itensdopedido.to_param}, valid_session
      assigns(:itensdopedido).should eq(itensdopedido)
    end
  end

  describe "GET new" do
    it "assigns a new itensdopedido as @itensdopedido" do
      get :new, {}, valid_session
      assigns(:itensdopedido).should be_a_new(Itensdopedido)
    end
  end

  describe "GET edit" do
    it "assigns the requested itensdopedido as @itensdopedido" do
      itensdopedido = Itensdopedido.create! valid_attributes
      get :edit, {:id => itensdopedido.to_param}, valid_session
      assigns(:itensdopedido).should eq(itensdopedido)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Itensdopedido" do
        expect {
          post :create, {:itensdopedido => valid_attributes}, valid_session
        }.to change(Itensdopedido, :count).by(1)
      end

      it "assigns a newly created itensdopedido as @itensdopedido" do
        post :create, {:itensdopedido => valid_attributes}, valid_session
        assigns(:itensdopedido).should be_a(Itensdopedido)
        assigns(:itensdopedido).should be_persisted
      end

      it "redirects to the created itensdopedido" do
        post :create, {:itensdopedido => valid_attributes}, valid_session
        response.should redirect_to(Itensdopedido.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved itensdopedido as @itensdopedido" do
        # Trigger the behavior that occurs when invalid params are submitted
        Itensdopedido.any_instance.stub(:save).and_return(false)
        post :create, {:itensdopedido => { "itempedido" => "invalid value" }}, valid_session
        assigns(:itensdopedido).should be_a_new(Itensdopedido)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Itensdopedido.any_instance.stub(:save).and_return(false)
        post :create, {:itensdopedido => { "itempedido" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested itensdopedido" do
        itensdopedido = Itensdopedido.create! valid_attributes
        # Assuming there are no other itensdopedidos in the database, this
        # specifies that the Itensdopedido created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Itensdopedido.any_instance.should_receive(:update).with({ "itempedido" => "MyString" })
        put :update, {:id => itensdopedido.to_param, :itensdopedido => { "itempedido" => "MyString" }}, valid_session
      end

      it "assigns the requested itensdopedido as @itensdopedido" do
        itensdopedido = Itensdopedido.create! valid_attributes
        put :update, {:id => itensdopedido.to_param, :itensdopedido => valid_attributes}, valid_session
        assigns(:itensdopedido).should eq(itensdopedido)
      end

      it "redirects to the itensdopedido" do
        itensdopedido = Itensdopedido.create! valid_attributes
        put :update, {:id => itensdopedido.to_param, :itensdopedido => valid_attributes}, valid_session
        response.should redirect_to(itensdopedido)
      end
    end

    describe "with invalid params" do
      it "assigns the itensdopedido as @itensdopedido" do
        itensdopedido = Itensdopedido.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Itensdopedido.any_instance.stub(:save).and_return(false)
        put :update, {:id => itensdopedido.to_param, :itensdopedido => { "itempedido" => "invalid value" }}, valid_session
        assigns(:itensdopedido).should eq(itensdopedido)
      end

      it "re-renders the 'edit' template" do
        itensdopedido = Itensdopedido.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Itensdopedido.any_instance.stub(:save).and_return(false)
        put :update, {:id => itensdopedido.to_param, :itensdopedido => { "itempedido" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested itensdopedido" do
      itensdopedido = Itensdopedido.create! valid_attributes
      expect {
        delete :destroy, {:id => itensdopedido.to_param}, valid_session
      }.to change(Itensdopedido, :count).by(-1)
    end

    it "redirects to the itensdopedidos list" do
      itensdopedido = Itensdopedido.create! valid_attributes
      delete :destroy, {:id => itensdopedido.to_param}, valid_session
      response.should redirect_to(itensdopedidos_url)
    end
  end

end
