require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrdemdeservicosController do

  # This should return the minimal set of attributes required to create a valid
  # Ordemdeservico. As you add validations to Ordemdeservico, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "descricaoservico" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdemdeservicosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ordemdeservicos as @ordemdeservicos" do
      ordemdeservico = Ordemdeservico.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ordemdeservicos).should eq([ordemdeservico])
    end
  end

  describe "GET show" do
    it "assigns the requested ordemdeservico as @ordemdeservico" do
      ordemdeservico = Ordemdeservico.create! valid_attributes
      get :show, {:id => ordemdeservico.to_param}, valid_session
      assigns(:ordemdeservico).should eq(ordemdeservico)
    end
  end

  describe "GET new" do
    it "assigns a new ordemdeservico as @ordemdeservico" do
      get :new, {}, valid_session
      assigns(:ordemdeservico).should be_a_new(Ordemdeservico)
    end
  end

  describe "GET edit" do
    it "assigns the requested ordemdeservico as @ordemdeservico" do
      ordemdeservico = Ordemdeservico.create! valid_attributes
      get :edit, {:id => ordemdeservico.to_param}, valid_session
      assigns(:ordemdeservico).should eq(ordemdeservico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ordemdeservico" do
        expect {
          post :create, {:ordemdeservico => valid_attributes}, valid_session
        }.to change(Ordemdeservico, :count).by(1)
      end

      it "assigns a newly created ordemdeservico as @ordemdeservico" do
        post :create, {:ordemdeservico => valid_attributes}, valid_session
        assigns(:ordemdeservico).should be_a(Ordemdeservico)
        assigns(:ordemdeservico).should be_persisted
      end

      it "redirects to the created ordemdeservico" do
        post :create, {:ordemdeservico => valid_attributes}, valid_session
        response.should redirect_to(Ordemdeservico.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ordemdeservico as @ordemdeservico" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ordemdeservico.any_instance.stub(:save).and_return(false)
        post :create, {:ordemdeservico => { "descricaoservico" => "invalid value" }}, valid_session
        assigns(:ordemdeservico).should be_a_new(Ordemdeservico)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ordemdeservico.any_instance.stub(:save).and_return(false)
        post :create, {:ordemdeservico => { "descricaoservico" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ordemdeservico" do
        ordemdeservico = Ordemdeservico.create! valid_attributes
        # Assuming there are no other ordemdeservicos in the database, this
        # specifies that the Ordemdeservico created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ordemdeservico.any_instance.should_receive(:update).with({ "descricaoservico" => "MyString" })
        put :update, {:id => ordemdeservico.to_param, :ordemdeservico => { "descricaoservico" => "MyString" }}, valid_session
      end

      it "assigns the requested ordemdeservico as @ordemdeservico" do
        ordemdeservico = Ordemdeservico.create! valid_attributes
        put :update, {:id => ordemdeservico.to_param, :ordemdeservico => valid_attributes}, valid_session
        assigns(:ordemdeservico).should eq(ordemdeservico)
      end

      it "redirects to the ordemdeservico" do
        ordemdeservico = Ordemdeservico.create! valid_attributes
        put :update, {:id => ordemdeservico.to_param, :ordemdeservico => valid_attributes}, valid_session
        response.should redirect_to(ordemdeservico)
      end
    end

    describe "with invalid params" do
      it "assigns the ordemdeservico as @ordemdeservico" do
        ordemdeservico = Ordemdeservico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ordemdeservico.any_instance.stub(:save).and_return(false)
        put :update, {:id => ordemdeservico.to_param, :ordemdeservico => { "descricaoservico" => "invalid value" }}, valid_session
        assigns(:ordemdeservico).should eq(ordemdeservico)
      end

      it "re-renders the 'edit' template" do
        ordemdeservico = Ordemdeservico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ordemdeservico.any_instance.stub(:save).and_return(false)
        put :update, {:id => ordemdeservico.to_param, :ordemdeservico => { "descricaoservico" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ordemdeservico" do
      ordemdeservico = Ordemdeservico.create! valid_attributes
      expect {
        delete :destroy, {:id => ordemdeservico.to_param}, valid_session
      }.to change(Ordemdeservico, :count).by(-1)
    end

    it "redirects to the ordemdeservicos list" do
      ordemdeservico = Ordemdeservico.create! valid_attributes
      delete :destroy, {:id => ordemdeservico.to_param}, valid_session
      response.should redirect_to(ordemdeservicos_url)
    end
  end

end
