require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TelefonefuncionariosController do

  # This should return the minimal set of attributes required to create a valid
  # Telefonefuncionario. As you add validations to Telefonefuncionario, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "numerotelefone" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TelefonefuncionariosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all telefonefuncionarios as @telefonefuncionarios" do
      telefonefuncionario = Telefonefuncionario.create! valid_attributes
      get :index, {}, valid_session
      assigns(:telefonefuncionarios).should eq([telefonefuncionario])
    end
  end

  describe "GET show" do
    it "assigns the requested telefonefuncionario as @telefonefuncionario" do
      telefonefuncionario = Telefonefuncionario.create! valid_attributes
      get :show, {:id => telefonefuncionario.to_param}, valid_session
      assigns(:telefonefuncionario).should eq(telefonefuncionario)
    end
  end

  describe "GET new" do
    it "assigns a new telefonefuncionario as @telefonefuncionario" do
      get :new, {}, valid_session
      assigns(:telefonefuncionario).should be_a_new(Telefonefuncionario)
    end
  end

  describe "GET edit" do
    it "assigns the requested telefonefuncionario as @telefonefuncionario" do
      telefonefuncionario = Telefonefuncionario.create! valid_attributes
      get :edit, {:id => telefonefuncionario.to_param}, valid_session
      assigns(:telefonefuncionario).should eq(telefonefuncionario)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Telefonefuncionario" do
        expect {
          post :create, {:telefonefuncionario => valid_attributes}, valid_session
        }.to change(Telefonefuncionario, :count).by(1)
      end

      it "assigns a newly created telefonefuncionario as @telefonefuncionario" do
        post :create, {:telefonefuncionario => valid_attributes}, valid_session
        assigns(:telefonefuncionario).should be_a(Telefonefuncionario)
        assigns(:telefonefuncionario).should be_persisted
      end

      it "redirects to the created telefonefuncionario" do
        post :create, {:telefonefuncionario => valid_attributes}, valid_session
        response.should redirect_to(Telefonefuncionario.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved telefonefuncionario as @telefonefuncionario" do
        # Trigger the behavior that occurs when invalid params are submitted
        Telefonefuncionario.any_instance.stub(:save).and_return(false)
        post :create, {:telefonefuncionario => { "numerotelefone" => "invalid value" }}, valid_session
        assigns(:telefonefuncionario).should be_a_new(Telefonefuncionario)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Telefonefuncionario.any_instance.stub(:save).and_return(false)
        post :create, {:telefonefuncionario => { "numerotelefone" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested telefonefuncionario" do
        telefonefuncionario = Telefonefuncionario.create! valid_attributes
        # Assuming there are no other telefonefuncionarios in the database, this
        # specifies that the Telefonefuncionario created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Telefonefuncionario.any_instance.should_receive(:update).with({ "numerotelefone" => "MyString" })
        put :update, {:id => telefonefuncionario.to_param, :telefonefuncionario => { "numerotelefone" => "MyString" }}, valid_session
      end

      it "assigns the requested telefonefuncionario as @telefonefuncionario" do
        telefonefuncionario = Telefonefuncionario.create! valid_attributes
        put :update, {:id => telefonefuncionario.to_param, :telefonefuncionario => valid_attributes}, valid_session
        assigns(:telefonefuncionario).should eq(telefonefuncionario)
      end

      it "redirects to the telefonefuncionario" do
        telefonefuncionario = Telefonefuncionario.create! valid_attributes
        put :update, {:id => telefonefuncionario.to_param, :telefonefuncionario => valid_attributes}, valid_session
        response.should redirect_to(telefonefuncionario)
      end
    end

    describe "with invalid params" do
      it "assigns the telefonefuncionario as @telefonefuncionario" do
        telefonefuncionario = Telefonefuncionario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Telefonefuncionario.any_instance.stub(:save).and_return(false)
        put :update, {:id => telefonefuncionario.to_param, :telefonefuncionario => { "numerotelefone" => "invalid value" }}, valid_session
        assigns(:telefonefuncionario).should eq(telefonefuncionario)
      end

      it "re-renders the 'edit' template" do
        telefonefuncionario = Telefonefuncionario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Telefonefuncionario.any_instance.stub(:save).and_return(false)
        put :update, {:id => telefonefuncionario.to_param, :telefonefuncionario => { "numerotelefone" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested telefonefuncionario" do
      telefonefuncionario = Telefonefuncionario.create! valid_attributes
      expect {
        delete :destroy, {:id => telefonefuncionario.to_param}, valid_session
      }.to change(Telefonefuncionario, :count).by(-1)
    end

    it "redirects to the telefonefuncionarios list" do
      telefonefuncionario = Telefonefuncionario.create! valid_attributes
      delete :destroy, {:id => telefonefuncionario.to_param}, valid_session
      response.should redirect_to(telefonefuncionarios_url)
    end
  end

end
